version: '3'

services:

  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - default
      - postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:rw

  admin:
    image: dpage/pgadmin4:6
    restart: unless-stopped
    ports:
      - 8032:80
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    volumes:
      - ./servers.json:/pgadmin4/servers.json:ro
      - ./data/pgadmin:/var/lib/pgadmin:rw

networks:
  postgres:
    name: postgres
